### ISSUE TITLE
SQlite support

### ISSUE THREAD

**Issue by rredpoppy** [crew-cr/Crew#109]
I imagine it's not so difficult, unless you have exotic SQL commands.

**Comment by maxailloud** [comment]
IMO it's just a propel configuration, so you should be able to configure Crew to use a SQlite database instead of a MySQL one.
Of course except if we use exotic commands, but I don't think this is the case.

Give it a try with SQlite and you will be fixe, and maybe you could make a PR to support SQlite if it's not the case ;)

**Comment by rredpoppy** [comment]
Thanks, I will give it a try
